### ISSUE TITLE
error: Error -3 while decompressing: incorrect header check

### ISSUE THREAD

**Issue by bamit99** [Incapsula/logs-downloader#34]
it is downloading log files but in Fail folder. Getting the error below within the /Var/Log file. I am not using any compression etc. The downloaded file format is LEEF and now I am stuck.

Qradar and Imperva

020-07-11 10:48:29,734 INFO Saving file XXX_XXXXXX.log locally to the 'fail' folder Error -3 while decompressing: incorrect header check Traceback (most recent call last):
  File "LogsDownloader.py", line 222, in handle_file
    decrypted_file = self.decrypt_file(result[1], logfile)
  File "LogsDownloader.py", line 280, in decrypt_file
    uncompressed_and_decrypted_file_content = zlib.decompressobj().decompress(file_log_content)
error: Error -3 while decompressing: incorrect header check

**Comment by bamit99** [comment]
Should have read the manual thoroughly :). This error comes if the compression is set to No. The script expects the data to be compressed.
